services:
  doc-rag-db:
    image: mongodb/mongodb-atlas-local:latest
    hostname: mongodb
    restart: unless-stopped
    container_name: doc-rag-db
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
      - "mongodb-config:/data/configdb"
    networks:
      - doc-rag

networks:
  doc-rag:
    name: doc-rag

volumes:
  mongodb-data:
  mongodb-config:
