services:
  doc-rag-db:
    image: mongo
    restart: unless-stopped
    container_name: doc-rag-db
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
    networks:
      - doc-rag

networks:
  doc-rag:
    name: doc-rag

volumes:
  mongodb-data: